name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run:  sudo apt-get install -y astyle lilv-utils lv2-dev
    - name: Build
      run: mkdir build && cd build && cmake .. && make
    - name: Install
      run: cd build && sudo make install
    - name: Test with lv2bench
      run: lv2bench
