name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-ubuntu-amd64:
    name: Ubuntu 22.04 (amd64)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Test with lv2bench
      run: lv2bench
    - uses: actions/upload-artifact@v3
      with:
        name: linux-amd64
        path: /usr/local/lib/x86_64-linux-gnu/lv2/Airwindows.lv2

  build-ubuntu-i686:
    name: Ubuntu 22.04 (i686)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y gcc-i686-linux-gnu lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build --cross-file cross/linux-i686.txt
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Test with lv2bench
      run: lv2bench
    - uses: actions/upload-artifact@v3
      with:
        name: linux-i686
        path: /usr/local/lib/x86_64-linux-gnu/lv2/Airwindows.lv2

  build-ubuntu-aarch64:
    name: Ubuntu 22.04 (aarch64)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y gcc-aarch64-linux-gnu lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build --cross-file cross/linux-aarch64.txt
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - uses: actions/upload-artifact@v3
      with:
        name: linux-aarch64
        path: /usr/local/lib/x86_64-linux-gnu/lv2/Airwindows.lv2

  build-ubuntu-armhf:
    name: Ubuntu 22.04 (armhf)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y gcc-arm-linux-gnueabihf lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build --cross-file cross/linux-armhf.txt
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - uses: actions/upload-artifact@v3
      with:
        name: linux-armhf
        path: /usr/local/lib/x86_64-linux-gnu/lv2/Airwindows.lv2

  build-macos:
    name: macOS 12 (amd64)
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: brew install lilv lv2 meson
    - name: Validate Turtle files
      run: lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Test with lv2bench
      run: lv2bench
    - uses: actions/upload-artifact@v3
      with:
        name: macos
        path: /usr/local/lib/lv2/Airwindows.lv2

  build-windows64:
    name: Windows (64-Bit)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-lv2
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-pkg-config
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup build directory
      env:
        CC: x86_64-w64-mingw32-gcc
      run: meson setup build
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: meson install -C build
    - uses: actions/upload-artifact@v3
      with:
        name: win64
        path: D:/a/_temp/msys64/mingw64/lib/lv2/Airwindows.lv2

  build-windows32:
    name: Windows (32-Bit)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-i686-gcc
          mingw-w64-i686-meson
          mingw-w64-i686-lv2
          mingw-w64-i686-ninja
          mingw-w64-i686-pkg-config
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup build directory
      env:
        CC: i686-w64-mingw32-gcc
      run: /mingw32/bin/meson.exe setup build
    - name: Compile
      run: /mingw32/bin/meson.exe compile -C build
    - name: Install
      run: /mingw32/bin/meson.exe install -C build
    - uses: actions/upload-artifact@v3
      with:
        name: win32
        path: D:/a/_temp/msys64/mingw32/lib/lv2/Airwindows.lv2
