name: Build

on:
  push:
    branches: '*'
    tags: 'v*'
  pull_request:
    branches: '*'

jobs:
  build-ubuntu-amd64:
    name: Ubuntu 22.04 (amd64)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Test with lv2bench
      run: lv2bench
    - name: Check presence of installation
      run: test -d /usr/local/lib/x86_64-linux-gnu/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-amd64-linux
        cp -r /usr/local/lib/x86_64-linux-gnu/lv2/Airwindows.lv2 airwindows-lv2-amd64-linux
        cp LICENSE airwindows-lv2-amd64-linux
        tar -cvzf airwindows-lv2-amd64-linux.tar.gz airwindows-lv2-amd64-linux
    - uses: actions/upload-artifact@v3
      with:
        name: amd64-linux
        path: airwindows-lv2-amd64-linux.tar.gz

  build-ubuntu-i686:
    name: Ubuntu 22.04 (i686)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y gcc-i686-linux-gnu lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build --cross-file cross/linux-i686.txt
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Test with lv2bench
      run: lv2bench
    - name: Check presence of installation
      run: test -d /usr/local/lib/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-i686-linux
        cp -r /usr/local/lib/lv2/Airwindows.lv2 airwindows-lv2-i686-linux
        cp LICENSE airwindows-lv2-i686-linux
        tar -cvzf airwindows-lv2-i686-linux.tar.gz airwindows-lv2-i686-linux
    - uses: actions/upload-artifact@v3
      with:
        name: i686-linux
        path: airwindows-lv2-i686-linux.tar.gz

  build-ubuntu-aarch64:
    name: Ubuntu 22.04 (aarch64)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y gcc-aarch64-linux-gnu lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build --cross-file cross/linux-aarch64.txt
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Check presence of installation
      run: test -d /usr/local/lib/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-aarch64-linux
        cp -r /usr/local/lib/lv2/Airwindows.lv2 airwindows-lv2-aarch64-linux
        cp LICENSE airwindows-lv2-aarch64-linux
        tar -cvzf airwindows-lv2-aarch64-linux.tar.gz airwindows-lv2-aarch64-linux
    - uses: actions/upload-artifact@v3
      with:
        name: aarch64-linux
        path: airwindows-lv2-aarch64-linux.tar.gz

  build-ubuntu-armhf:
    name: Ubuntu 22.04 (armhf)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y gcc-arm-linux-gnueabihf lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build --cross-file cross/linux-armhf.txt
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Check presence of installation
      run: test -d /usr/local/lib/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-armhf-linux
        cp -r /usr/local/lib/lv2/Airwindows.lv2 airwindows-lv2-armhf-linux
        cp LICENSE airwindows-lv2-armhf-linux
        tar -cvzf airwindows-lv2-armhf-linux.tar.gz airwindows-lv2-armhf-linux
    - uses: actions/upload-artifact@v3
      with:
        name: armhf-linux
        path: airwindows-lv2-armhf-linux.tar.gz

  build-macos-amd64:
    name: macOS 12 (amd64)
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: brew install lilv lv2 meson
    - name: Validate Turtle files
      run: lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Test with lv2bench
      run: lv2bench
    - name: Check presence of installation
      run: test -d /usr/local/lib/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-amd64-macos
        cp -r /usr/local/lib/lv2/Airwindows.lv2 airwindows-lv2-amd64-macos
        cp LICENSE airwindows-lv2-amd64-macos
        tar -cvzf airwindows-lv2-amd64-macos.tar.gz airwindows-lv2-amd64-macos
    - uses: actions/upload-artifact@v3
      with:
        name: amd64-macos
        path: airwindows-lv2-amd64-macos.tar.gz

  build-macos-aarch64:
    name: macOS 12 (aarch64)
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: brew install lilv lv2 meson
    - name: Validate Turtle files
      run: lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build --cross-file cross/macos-aarch64.txt
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Check presence of installation
      run: test -d /usr/local/lib/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-aarch64-macos
        cp -r /usr/local/lib/lv2/Airwindows.lv2 airwindows-lv2-aarch64-macos
        cp LICENSE airwindows-lv2-aarch64-macos
        tar -cvzf airwindows-lv2-aarch64-macos.tar.gz airwindows-lv2-aarch64-macos
    - uses: actions/upload-artifact@v3
      with:
        name: aarch64-macos
        path: airwindows-lv2-aarch64-macos.tar.gz

  build-windows-amd64:
    name: Windows (amd64)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-lv2
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-pkg-config
          zip
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup build directory
      env:
        CC: x86_64-w64-mingw32-gcc
      run: meson setup build
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: meson install -C build
    - name: Check presence of installation
      run: test -d D:/a/_temp/msys64/mingw64/lib/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-amd64-windows
        cp -r D:/a/_temp/msys64/mingw64/lib/lv2/Airwindows.lv2 airwindows-lv2-amd64-windows
        rm airwindows-lv2-amd64-windows/Airwindows.lv2/*.a
        cp LICENSE airwindows-lv2-amd64-windows
        zip -v -r airwindows-lv2-amd64-windows.zip airwindows-lv2-amd64-windows
    - uses: actions/upload-artifact@v3
      with:
        name: amd64-windows
        path: airwindows-lv2-amd64-windows.zip

  build-windows-i686:
    name: Windows (i686)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-i686-gcc
          mingw-w64-i686-meson
          mingw-w64-i686-lv2
          mingw-w64-i686-ninja
          mingw-w64-i686-pkg-config
          zip
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup build directory
      env:
        CC: i686-w64-mingw32-gcc
      run: /mingw32/bin/meson.exe setup build
    - name: Compile
      run: /mingw32/bin/meson.exe compile -C build
    - name: Install
      run: /mingw32/bin/meson.exe install -C build
    - name: Check presence of installation
      run: test -d D:/a/_temp/msys64/mingw32/lib/lv2/Airwindows.lv2
    - name: Package
      run: |
        mkdir airwindows-lv2-i686-windows
        cp -r D:/a/_temp/msys64/mingw32/lib/lv2/Airwindows.lv2 airwindows-lv2-i686-windows
        rm airwindows-lv2-i686-windows/Airwindows.lv2/*.a
        cp LICENSE airwindows-lv2-i686-windows
        zip -v -r airwindows-lv2-i686-windows.zip airwindows-lv2-i686-windows
    - uses: actions/upload-artifact@v3
      with:
        name: i686-windows
        path: airwindows-lv2-i686-windows.zip

  release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-ubuntu-amd64
      - build-ubuntu-i686
      - build-ubuntu-aarch64
      - build-ubuntu-armhf
      - build-macos-amd64
      - build-macos-aarch64
      - build-windows-amd64
      - build-windows-i686
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Parse release name
        id: parse-release-name
        run: echo ::set-output name=rname::$(echo ${{ github.ref_name }} | cut -c 2-)
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.parse-release-name.outputs.rname }}
          files: |
            amd64-linux/airwindows-lv2-amd64-linux.tar.gz
            i686-linux/airwindows-lv2-i686-linux.tar.gz
            aarch64-linux/airwindows-lv2-aarch64-linux.tar.gz
            armhf-linux/airwindows-lv2-armhf-linux.tar.gz
            amd64-macos/airwindows-lv2-amd64-macos.tar.gz
            aarch64-macos/airwindows-lv2-aarch64-macos.tar.gz
            amd64-windows/airwindows-lv2-amd64-windows.zip
            i686-windows/airwindows-lv2-i686-windows.zip
