name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y astyle lilv-utils lv2-dev meson sordi
    - name: Validate Turtle files
      run: /usr/bin/lv2_validate src/manifest.ttl.in src/*/*.ttl
    - name: Setup build directory
      run: meson setup build
    - name: Compile
      run: meson compile -C build
    - name: Install
      run: sudo meson install -C build
    - name: Test with lv2bench
      run: lv2bench
